string sort(nodejs, golang)
mad-app/coding-test pull request #2
Opened 2022-06-30 06:52 UTC by leechanhui1234

nodejs, golang sort complete.(leechanhui)

2022-07-01 02:00 UTC, 5pecia1 requested changes
go, node 두가지 다 비슷한 코드라 비슷한 문제는 한쪽만 코멘트 달았습니다.
수정 후 다시 Re-request review 요청 해주세요.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +var alphabatdata = [30]int{0}               //알파벳 인덱스에 해당하는 데이터의 개수
길이가 `30`인 이유가 있을까요?

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +var alphabat = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" //해당 인덱스에 해당하는 알파벳
상수로 하는게 좋을 것 같습니다.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +	for i := 0; i < 26; i++ {
`alphabat`변수의 길이로 하는게 좋을것 같네요

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +			continue
굳이 `continue` 없어도 로직상 문제 없지 않을까요

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +	if b == false {
`bool`값을 `bool`로 비교하는건 좋지 않습니다.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.go
> +		var s string = sortstr(text)
```suggestion
		s := sortstr(text)
```

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +var alphabat = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"; //해당 인덱스에 해당하는 알파벳
위와 동일합니다.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +  var c = true;
`var`보다 `let` 사용을 지향합니다.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +const readline = require("readline"); //readline을 하기 위한 하나의 모듈
모듈은 코드 가장 위에서 한번에 import 하는것이 좋습니다.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +  str = line;
따로 할당은 하는 이유가 있나요? `line`을 그대로 사용해도 될것 같네요.

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +  var c = check(str);
변하지 않는 값은 `const`로

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +var str = ""; //문자열 저장 변수
여기서 문자열 저장 변수를 전역으로 따로 만들 이유가 있을까요?

2022-07-01 02:00 UTC, 5pecia1 commented on chanhui/homework.js
> +}); //문자열 한 번 입력받음
가능하면 대부분의 코드는 스코프를 제한했으면 좋겠습니다.
go처럼 `main()`함수에 넣어 주세요.

2022-07-02 00:05 UTC, leechanhui1234 commented on chanhui/homework.go
> +var alphabatdata = [30]int{0}               //알파벳 인덱스에 해당하는 데이터의 개수
메모리를 넉넉하게 잡아 30으로 했었으나 알파벳 개수가 26개라 사이즈를 26으로 수정했습니다.

2022-07-02 00:05 UTC, leechanhui1234 commented on chanhui/homework.go
> +var alphabat = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" //해당 인덱스에 해당하는 알파벳
상수로 수정했습니다.

2022-07-02 00:06 UTC, leechanhui1234 commented on chanhui/homework.go
> +	for i := 0; i < 26; i++ {
넵. alphabat 변수 길이 len(alphabat)으로 수정했습니다.

2022-07-02 00:06 UTC, leechanhui1234 commented on chanhui/homework.go
> +			continue
continue 없애고 'A'~'Z'까지 속하지 않으면 바로 break 시켜주는 형식으로 바꿔줬습니다.

2022-07-02 00:07 UTC, leechanhui1234 commented on chanhui/homework.js
> +const readline = require("readline"); //readline을 하기 위한 하나의 모듈
최상단에 import문을 하도록 수정해주었습니다.

2022-07-02 00:07 UTC, leechanhui1234 commented on chanhui/homework.js
> +  str = line;
str을 없애고 line을 바로 쓰도록 수정해주었습니다.

2022-07-02 00:08 UTC, leechanhui1234 commented on chanhui/homework.js
> +  var c = check(str);
저 변수 선언문을 없애고 코드상에서 바로 check(str)값을 출력할 수 있도록 수정을 해주었습니다.

2022-07-02 00:09 UTC, leechanhui1234 commented on chanhui/homework.js
> +var str = ""; //문자열 저장 변수
위에서 말했듯이 변수 선언문을 없애고 line을 바로 사용할 수 있게끔 수정을 해 주었습니다.

2022-07-02 00:09 UTC, leechanhui1234 commented on chanhui/homework.js
> +}); //문자열 한 번 입력받음
main함수 내에서 코드들을 작성하도록 수정해주었습니다.

2022-07-02 00:11 UTC, leechanhui1234 commented on chanhui/homework.go
> +	if b == false {
bool을 bool로 비교하는 코드를 지우고 !check(text) 형식으로 if문 내에서 바로 체크할 수 있도록 수정해주었습니다.

2022-07-04 05:24 UTC, 5pecia1 commented on chanhui/homework.js
> +  const alphabatnum = Array.from({ length: 30 }, (v, i) => 0); //해당 문자의 인덱스를 담기 위한 변수
```suggestion
  const alphabatnum = Array.from({ length: 26 }, (v, i) => 0); //해당 문자의 인덱스를 담기 위한 변수
```

2022-07-05 08:17 UTC, leechanhui1234 commented on chanhui/homework.js
> +  const alphabatnum = Array.from({ length: 30 }, (v, i) => 0); //해당 문자의 인덱스를 담기 위한 변수
nodejs 배열 사이즈까지 수정 완료했습니다.

2022-07-08 06:29 UTC, 5pecia1 commented
Thanks!

2022-07-08 06:29 UTC, closed without merging