Leejongin sort(go,node)
mad-app/coding-test pull request #3
Opened 2022-06-30 07:22 UTC by massivefox

2022-07-01 02:07 UTC, sangdo90 commented on sort.js
> +  return myRegExp(abc)
@massivefox 
`compare_abc` 함수가 실행이 되던가요?
정규표현식 체킹하는 메서드가 따로 있던걸로 아는데 이렇게 해도 동작하는지 궁금하네요

2022-07-01 02:17 UTC, 5pecia1 requested changes
go, node 두가지 다 비슷한 코드라 비슷한 문제는 한쪽만 코멘트 달았습니다.
수정 후 다시 Re-request review 요청 해주세요.

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +func compare_abc(s string) bool {
snake case는 go coding convention에 맞지 않습니다.

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +func IsUpper(s string) string {
보통 `Is`로 시작하는 건 `bool`을 리턴합니다.

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +	if IsUpper(str) != str {
```suggestion
	if strings.ToUpper(str) != str {
```

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +	} else if compare_abc(str) == true {
bool비교는 좋지 않습니다.

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +		str1 := str
재할당 하는 이유가 있나요

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +		sum := strings.Join(cut1, "")
`sum`은 어떤 의미로 사용했나요?

2022-07-01 02:17 UTC, 5pecia1 commented on main.go
> +		cut1 := strings.Split(str1, "")
`cut1`의 의미는?

2022-07-01 02:17 UTC, 5pecia1 commented on sort.js
> +  const upper =input.toUpperCase();
lint가 안 맞아요

2022-07-01 02:17 UTC, 5pecia1 commented on sort.js
> +  const abc = input;
재할당 할 필요 없을 것 같네요

2022-07-01 02:17 UTC, 5pecia1 commented on sort.js
> +  var str='';
`var`보다 `let` 사용을 지향합니다.

2022-07-01 02:17 UTC, 5pecia1 commented on sort.js
> +  var Split = str.split('');
node.js에서는 대체로 변수이름은 대문자로 시작하지 않습니다.

2022-07-08 06:30 UTC, 5pecia1 commented
Thanks!

2022-07-08 06:30 UTC, closed without merging