Shinhyejin sort(go-lang,node.js)
mad-app/coding-test pull request #4
Opened 2022-06-30 07:54 UTC by toki0411

2022-07-01 02:19 UTC, sangdo90 commented
@toki0411 
정렬 기능은 잘해주셨는데 알파벳 대문자 제한 기능은 없는것 같아요.

2022-07-01 02:29 UTC, 5pecia1 requested changes
go, node 두가지 다 비슷한 코드라 비슷한 문제는 한쪽만 코멘트 달았습니다.
수정 후 다시 Re-request review 요청 해주세요.

2022-07-01 02:29 UTC, 5pecia1 commented on task.go
> +	fmt.Println(string(quickSort(b))) //2번 방법 - 퀵소트 사용
참고로 최신 go는 내부적으로 Pattern-defeating QuickSort를 사용합니다.

2022-07-01 02:29 UTC, 5pecia1 commented on task.go
> +func main() {
`입력은 알파벳 대문자로 제한`에 대한 내용이 없네요

2022-07-01 02:29 UTC, 5pecia1 commented on task.js
> +    var arr=[]
`var`보다 `let`사용을 지향합니다.

2022-07-01 02:29 UTC, 5pecia1 commented on task.js
> +    var arr2=""
lint가 안맞아요

2022-07-01 02:29 UTC, 5pecia1 commented on task.js
> +
여긴 영문자를 입력해 달라는 말이 없네요.

2022-07-01 02:29 UTC, 5pecia1 commented on task.js
> +
가능하면 대부분의 코드는 스코프 범위를 제한했으면 좋겠습니다.
go처럼 main()함수에 넣어 주세요.

2022-07-04 05:27 UTC, 5pecia1 commented on task.js
> +
@toki0411 본 내용 확인해 주세요.

2022-07-04 05:27 UTC, 5pecia1 requested changes

2022-07-04 05:27 UTC, 5pecia1 commented on index.js
> +    for(let i=0;i<line.length;i++){
lint가 안맞아요

2022-07-08 06:32 UTC, 5pecia1 commented
Thanks!

2022-07-08 06:32 UTC, closed without merging