Seyeon Go test
mad-app/coding-test pull request #6
Opened 2022-06-30 12:58 UTC by GSY6690

2022-07-01 02:28 UTC, sangdo90 commented
@GSY6690 
입력값 예시가 고정되어있는데  입력값을 소문자로 변경해도 잘 나올것 같네요. 
대문자 입력 제한하는 기능이 필요해 보입니다.

2022-07-01 02:32 UTC, 5pecia1 requested changes
* `입력은 알파벳 대문자로 제한`이라고 나와 있는데 입력을 할 수가 없네요.

2022-07-01 02:32 UTC, 5pecia1 commented on array.js
> +console.log([...string].sort().join(''))
가능하면 대부분의 코드는 스코프 범위를 제한했으면 좋겠습니다.
go처럼 main()함수에 넣어 주세요.

2022-07-01 02:32 UTC, 5pecia1 commented on array.js
> +var string = "BANANA";
`var`을 사용한 이유가 있나요

2022-07-08 06:32 UTC, 5pecia1 commented
Thanks!

2022-07-08 06:32 UTC, closed without merging